### ISSUE TITLE
Moon Phase is stuck at full moon.

### ISSUE THREAD

**Issue by Cyprex** [Thyriel/Minecraft-AEONs#10]
Moon phase is stuck at full moon, see https://github.com/CreativeMD/OpticManager/issues/7

**Comment by Thyriel** [comment]
I will remove OpticManager / IGCF anyway with the new update and replace it by "Extended Days". Should fix that too then

**Comment by Cyprex** [comment]
It's been fixed in OpticManager already.
https://github.com/CreativeMD/OpticManager/issues/7

**Comment by Thyriel** [comment]
Doesn't matter. I was anyway never 100% happy with that mod (used it only because it was the only way to alter day/night length) as it had some side effects (like client brightness setting disabled) and the "Extended Days" mod time bar is a pretty nice addition too.
