### ISSUE TITLE
Gaia Guardian does not drop Gaia Spirit

### ISSUE THREAD

**Issue by Cyprex** [Thyriel/Minecraft-AEONs#12]
Exactly as it says in the title, we've killed him several times now and haven't gotten any gaia spirit drops. Heart Crystals and IE shader bags do drop.

**Comment by Cyprex** [comment]
mods.ltt.LootTable.removeGlobalItem("botania:manaresource");
is what removes it, botania:manaresource is gaia spirit.
https://github.com/Vazkii/Botania/blob/96c352616e42f759714941909e6c8c40213b711a/src/main/resources/assets/botania/loot_tables/gaia_guardian.json

**Comment by Thyriel** [comment]
Thanks for the report. Seems that was an unintended sideeffect that should only remove botania ingots (same id) from dungeon chests that was added after i tested through botania bosses.
I will upload you a hotfix (scripts to be replaced) to fix this.

**Comment by Thyriel** [comment]
Hotfix:
https://github.com/Thyriel/Minecraft-AEONs/tree/master/gaiafix1.4/
- replace "scripts/LootTableTweaker/removevanilla.zs" file
- add "scripts/LootTweaker/botania.zs" file

removanilla.zs now doesn't touch botania:manaresource
botania.zs removes the manasteel ingots from chests as well as increasing the Gaia spirit drops from Gaia Boss and drastically increasing it from the advanced Gaia Boss. (default of 6 to 8, which is enough for 1-2 gaiaspirit/gaia steel ingots per boss seemed a bit low , which would mean that you had to kill like 25-30 bosses just for the Gaia Steel quest).
Would be great if you let me know if the gaia spirit amount droped now is fine or too much.

edit: If you play on a server you only need to replace these files on the server and not the clients.

**Comment by Cyprex** [comment]
Drop rate seems fine as it is right now.
