### ISSUE TITLE
Railgun firing nothing

### ISSUE THREAD

**Issue by Nailz2041** [Thyriel/Minecraft-AEONs#14]
Whenever we try to fire the rail-gun it charges up but when the button is released to fire it makes the firing sound and consumes the rod but nothing is actually fired doing no damage to the mob fired at and if fired at the ground it dose not leave the rod to be retrieved.

**Comment by Cyprex** [comment]
see https://github.com/BluSunrize/ImmersiveEngineering/issues/2714

**Comment by Thyriel** [comment]
nothing i can do about it as IE didn't release a new version the last months
