### ISSUE TITLE
Mob Spawners can be moved using Carry On

### ISSUE THREAD

**Issue by Cyprex** [Thyriel/Minecraft-AEONs#7]
Mob Spawners can be moved by picking them up with Carry On, is this intended? It's easily abusable with Roguelike Dungeons (as well as Twilight Forest, but that's an inferior method).
![2018-01-09_20 31 11](https://user-images.githubusercontent.com/35031555/34908357-6c79a89c-f88e-11e7-9987-1207e9aab652.png)

**Comment by Thyriel** [comment]
Yes this is an intended feature i had in mind when adding CarryOn ;)

**Comment by Cyprex** [comment]
Alright, I feel like being able to grab 30+ spawners in about an hour is quite op but your call.

**Comment by Thyriel** [comment]
It's more laggy then OP, especially as you need very good equipment in the higher level areas and for blights. The drops from the mobs (=mobfarms) have been altered too so you should not be able to farm big amounts of metal that way (if something still drops that gives you massive amounts of iron / etc. let me know please).
Also as they can spawn blights abusing that mechanic will drastically increase the area level which will make it harder and harder for you.

But technically a mobfarm like that was intended to be a good source of medium enchanted armor so you will be able to survive in medium level areas (<100) when you are around obsidian age as you likely will have to travel quite far for all the needed resources.
Later on, in high level areas those drops don't help anyway as even with fully enchanted Botania armor and buffs it's hard to survive in lvl 200+ areas.

**Comment by Thyriel** [comment]
With some upcoming changes in 1.5 (Mutated mobs inside Dungeons) the ability to carry spawners around will be disabled
