### ISSUE TITLE
Invalid Enchants on looted item.

### ISSUE THREAD

**Issue by Cyprex** [Thyriel/Minecraft-AEONs#8]
I obtained an item with all enchants, duplicated many times, in a roguelike dungeon. Unfortunately i do not know whether it dropped from a mob or i looted it from a chest. I'd be glad to direct the issue upstream if you have an idea which mod causes it.
![2018-01-10_02 05 40](https://user-images.githubusercontent.com/35031555/34908363-9684892c-f88e-11e7-98c7-1b8abdc8f8d0.png)

**Comment by Cyprex** [comment]
I think i narrowed this down to the mod that spawns zombies with higher than normal HP(~130-200 for me currently)

**Comment by Thyriel** [comment]
How come that you think that it's that mod ?
I've seen one such item myself, and i always thought it would be the script mod that i use to rewrite the loottables of the chests and mobs. (But i couldn't figure out how these OP Items are generated as all the script does is adding armor pieces with random enchantments)

**Comment by Cyprex** [comment]
based on the armor drops i got, you might to consider items which have invalid enchants like 2 of any protection on armor(feather falling fire protection etc.)
Although what you say might well be true, the mobs spawning with increased health might just spawn with equipment more often, or have a higher chance to drop their equipment.

**Comment by Cyprex** [comment]
see https://github.com/SilentChaos512/ScalingHealth/issues/70 , this can cause crashes as well. It's fixed in the latest version of Scaling Health, so you might want to update.

**Comment by Thyriel** [comment]
Should be fixed with modupdate in 1.5
