### ISSUE TITLE
Barracks 4 requires currently uncraftable Iron Swords

### ISSUE THREAD

**Issue by Cyprex** [Thyriel/Minecraft-AEONs#9]
The wooden Barracks Tier 4 requires Iron Swords, which are currently uncraftable.

**Comment by Thyriel** [comment]
Thanks for the report. (I'd really need somewhen to test through all the building tiers).
Will try if i can find a solution. (Maybe i can somehow edit the swords attack to zero and reenable crafting it) but will take a while as i just started to work on a new update.

**Comment by Cyprex** [comment]
Well i think Scaling Health update should take priority as that's a stability critical bug(#8). As for vanilla tools, if you can attach tooltips like "only useful for crafting" to them I'd try doing that, Iguanatweaks used to do that.

**Comment by Thyriel** [comment]
I don't think a bug that was undetected in a popular mod for months is critical enough to deserve a hotfix.

**Comment by Thyriel** [comment]
In 1.5 (hopefully ready in a few days) the Iron sword can now be found in roguelike dungeons on floor level 4
